### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by elgriego90** [MadCatMining/codeswholesale-woocommerce#1]
Hi how are you? I just try to install the plugin but is not working. When I activate the plugin ive got a fatal error 

Warning: require(C:\xampp2021\htdocs\cdkeys2\wp-content\plugins\codeswholesale-woocommerce-main\vendor\composer/../guzzlehttp/promises/src/functions_include.php): failed to open stream: No such file or directory in C:\xampp2021\htdocs\cdkeys2\wp-content\plugins\codeswholesale-woocommerce-main\vendor\composer\autoload_real.php on line 66

Also seems to be so light the package. I thinks there are some files that are not uploaded.

thnak you for ur time!!

Have  anice day.

**Comment by MadCatMining** [comment]
Let me check. Perhaps something got lost on the way. Been uploading through web interface here.

**Comment by MadCatMining** [comment]
Re-commited a full plugin code via git cli just to be sure that there's nothing left behind. 
All files seem to be in place. Small revert in a Product.php file to the version on which this repo is based (v.2.5.4). 

Re-download the code and see if that worked. Otherwise - plugin might be operational only under linux OS (you seem to be running it under xampp in windows, but the file paths are of a linux type). 

The whole package consists of 2243 files and a dir is 23.5Mb.

**Comment by elgriego90** [comment]
Hi how are you!! thank you so much for your quick response.

When i download the zip code, it only size 435kb, Am I doing somthing wrong?

Thanks in advance.

**Comment by MadCatMining** [comment]
If you download it from here - it should contain the whole repo.

![Screenshot_2023-04-14-15-34-15-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/17141973/232045153-2efb523d-86ce-4bb0-a23b-2395dbf620cd.jpg)

It was taken from a working project. So i can confirm that this code os working on a Linux based servers.

**Comment by elgriego90** [comment]
Hi thank you for your time. Here you have a pciture of the size of the package. What do you think? Is there anyway to contact you directly? :)

![Captura de pantalla 2023-04-14 a las 09 59 51](https://user-images.githubusercontent.com/130670483/232050566-91a0847e-2cba-4fa0-a459-1acefaec98b1.png)

**Comment by MadCatMining** [comment]
In discord at CWS server, #woocommecre channel.

https://discord.com/channels/468776612524195840/470891358576443392

**Comment by elgriego90** [comment]
May I ask you your username to add you? thanks in advance :)

**Comment by MadCatMining** [comment]
[MadCatMining]#0677
Full id: 446081437301604352

**Comment by elgriego90** [comment]
thank you! send it!

**Comment by elgriego90** [comment]
Hi Mad again. May I ask you for a google drive link, firts and formost, thank you for ur time! I really apreciate what you are doing.

**Comment by elgriego90** [comment]
Thank you MadCatMining. It was an error of the link!
